# Default configuration for training CRIS on SceneFun3D

# Model Architecture (CRIS defaults, user should verify/override for their specific CRIS variant)
clip_pretrain: "pretrain/RN50.pt" # USER MUST OVERRIDE THIS with actual path to a valid CLIP model
word_len: 77                     # Standard CLIP context length                # Dimension for the visual features input to the Transformer decoder, should match FPN output channel
fpn_in: [512, 1024, 1024]      # Input channels for FPN from backbone. For RN50, this is typically [512, 1024, 2048] if using C3,C4,C5.
                                 # Adjusted to [512, 1024, 1024] based on common CRIS configs, assuming C5 might be adapted or a different feature level is used.
                                 # The key is that fpn_in[1] must match the 1024 channels of v4.
fpn_out: [256, 512, 1024]        # Output channels for FPN layers. FPN's final output channel (e.g. fpn_out[1] if vis_dim is taken from mid FPN) should match vis_dim.
sync_bn: True                   # Whether to use SyncBatchNorm

# Decoder (Transformer)
num_layers: 3                    # Number of layers in Transformer decoder
num_head: 8                      # Number of attention heads
dim_ffn: 1024                    # Dimension of feed-forward network in Transformer (often 4 * vis_dim)
dropout: 0.1                     # Dropout rate in Transformer
intermediate: False              # Whether the Transformer decoder returns intermediate layer outputs

# Data and Dataloaders
# train_data_dir and val_data_dir MUST be provided in the user's specific config file
train_data_dir: "/cluster/scratch/andrye/SF3D_lmdb"
input_size: [416, 416]           # Image input size (height, width)
batch_size_train: 16
batch_size_val: 16
num_workers_train: 24
num_workers_val: 24

# Optimizer & Scheduler
optimizer_lr: 0.000005
optimizer_weight_decay: 0.000005
scheduler_milestones: [20, 25]   # Epochs at which to decay learning rate
scheduler_gamma: 0.1             # LR decay factor

# Loss functions
loss_bce_weight: 0.5             # Weight for BCE loss in DiceBCELoss
loss_dice_weight: 0.5            # Weight for Dice loss in DiceBCELoss
loss_point_sigma: 8.0            # Sigma for Gaussian heatmap generation (in pixels on the feature map)
loss_coord_weight: 0.5          # Weight for the L1 coordinate regression loss

# Trainer settings
max_epochs: 30
gpus: 2                          # Number of GPUs to use. If 1, uses GPU 0. If >1, uses specified number of GPUs. If 0, uses CPU.
precision: 32                    # 32 for float32, 16 for mixed-precision
exp_name: "SF3D_V4"
output_dir: "/cluster/scratch/andrye/experiments/SF3D_V4" # Base directory for outputs, will be exp_name within this.
manual_seed: 42
enable_wandb: True              # Set to true to enable Weights & Biases logging
wandb_project: "SceneFun3D-V4" # WandB project name
# wandb_entity: "your_wandb_entity" # Optional: WandB entity (username or team) 

wandb_show_loading_bar: True
val_split_ratio: 0.1
